merchandise:
  db: "cinemaug_merchandise"
  user: "root"
  host: "localhost"
  pass: "password"

mail:
  port: 465
  user: "info@nakimulifoundation.org"
  host: "server1.thinkxcloud.com"
  pass: "RfG9REST4KfzXvp"
